apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: us-east1-docker.pkg.dev/codematic-capstone-project/task-mgmt-api/app:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: POSTGRES_SERVER
              value: "postgres" # This references the postgres service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "task_management"
          ports:
            - containerPort: 8000
